In [1]:
import numpy as np
import cv2
from keras.preprocessing import image
import time



Using TensorFlow backend.


In [2]:
#opencv initialization

face_cascade = cv2.CascadeClassifier('/home/topica/anaconda3/envs/workspace/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml')

In [3]:
from keras.models import model_from_json
# model = model_from_json(open("/home/thaovu/tensorflow-101/model/facial_expression_model_structure.json", "r").read())
# model.load_weights('/home/thaovu/tensorflow-101/model/facial_expression_model_weights.h5') #load weights
model = model_from_json(open("/home/topica/workspace/Facial-Expression-Recognition/model_4layer_2_2_pool.json", "r").read())
model.load_weights('/home/topica/workspace/Facial-Expression-Recognition/model_4layer_2_2_pool.h5') #load weights

In [4]:
emotions = ('angry', 'disgust', 'fear', 'happy', 'sad', 'surprise', 'neutral')

In [6]:
cap = cv2.VideoCapture("/home/topica/Downloads/2018-07-01_21h.wmv")
fps = cap.get(cv2.CAP_PROP_FPS)
print ("Frames per second using video.get(cv2.CAP_PROP_FPS) : {0}".format(fps))
# cap = cv2.VideoCapture("/home/topica/Video_topica/T6_08_20180816_090000.avi")
frame = 0

# fourcc = cv2.VideoWriter_fourcc(*'MJPG')
# out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))
# out = cv2.VideoWriter('outpy.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 20, (1024,700))

while(True):
    ret, img = cap.read()
    print(img.shape)
    print(img)

    # img = cv2.resize(img, (640, 360))
#     img = img[0:308,:]

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    for (x,y,w,h) in faces:
    #     if w > 130: #trick: ignore small faces
            #cv2.rectangle(img,(x,y),(x+w,y+h),(64,64,64),2) #highlight detected face

            detected_face = img[int(y):int(y+h), int(x):int(x+w)] #crop detected face
            detected_face = cv2.cvtColor(detected_face, cv2.COLOR_BGR2GRAY) #transform to gray scale
            detected_face = cv2.resize(detected_face, (48, 48)) #resize to 48x48

            img_pixels = image.img_to_array(detected_face)
            img_pixels = np.expand_dims(img_pixels, axis = 0)

            img_pixels /= 255 #pixels are in scale of [0, 255]. normalize all pixels in scale of [0, 1]

            #------------------------------

            predictions = model.predict(img_pixels) #store probabilities of 7 expressions
            max_index = np.argmax(predictions[0])

            #background of expression list
            overlay = img.copy()
            opacity = 0.4
            cv2.rectangle(img,(x+w+10,y-25),(x+w+150,y+115),(64,64,64),cv2.FILLED)
            cv2.addWeighted(overlay, opacity, img, 1 - opacity, 0, img)

            #connect face and expressions
            cv2.line(img,(int((x+x+w)/2),y+15),(x+w,y-20),(255,255,255),1)
            cv2.line(img,(x+w,y-20),(x+w+10,y-20),(255,255,255),1)

            emotion = ""
            for i in range(len(predictions[0])):
                emotion = "%s %s%s" % (emotions[i], round(predictions[0][i]*100, 2), '%')

                """if i != max_index:
                    color = (255,0,0)"""

                color = (255,255,255)

                cv2.putText(img, emotion, (int(x+w+15), int(y-12+i*20)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)
                

            #-------------------------
#     out.write(frame)    
    cv2.imshow('img',img)

    frame = frame + 1
    #print(frame)

    #---------------------------------

#     if frame > 227:
#         break

    if cv2.waitKey(70) & 0xFF == ord('q'): #press q to quit
        break

#kill open cv things
# out.release()
# cap.release()
cv2.destroyAllWindows()

Frames per second using video.get(cv2.CAP_PROP_FPS) : 10.0
(992, 1920, 3)
[[[201 201 201]
  [144 144 144]
  [143 143 143]
  ...
  [ 58  58  58]
  [ 58  58  58]
  [ 58  58  58]]

 [[201 201 201]
  [144 144 144]
  [143 143 143]
  ...
  [ 58  58  58]
  [ 58  58  58]
  [ 58  58  58]]

 [[201 201 201]
  [144 144 144]
  [143 143 143]
  ...
  [ 58  58  58]
  [ 58  58  58]
  [ 58  58  58]]

 ...

 [[  0   0   0]
  [ 47  47  47]
  [ 48  48  48]
  ...
  [ 39  39  39]
  [ 39  39  39]
  [ 39  39  39]]

 [[  0   0   0]
  [ 47  47  47]
  [ 48  48  48]
  ...
  [ 39  39  39]
  [ 39  39  39]
  [ 39  39  39]]

 [[  0   0   0]
  [ 47  47  47]
  [ 48  48  48]
  ...
  [ 39  39  39]
  [ 39  39  39]
  [ 39  39  39]]]
(992, 1920, 3)
[[[201 201 201]
  [144 144 144]
  [143 143 143]
  ...
  [ 58  58  58]
  [ 58  58  58]
  [ 58  58  58]]

 [[201 201 201]
  [144 144 144]
  [143 143 143]
  ...
  [ 58  58  58]
  [ 58  58  58]
  [ 58  58  58]]

 [[201 201 201]
  [144 144 144]
  [143 143 143]
  ...
  [ 58  58  58]
  [